# Teeswim Mockup Service Configuration

[server]
host = "0.0.0.0"
port = 8080

[templates]
path = "./assets/templates"
cache_enabled = true

[cloudinary]
cloud_name = ""
api_key = ""
api_secret = ""
upload_preset = "mockups"

[performance]
max_concurrent_requests = 1000
request_timeout_seconds = 30
